#include "main.h"

CGlobalVars *Globals;
IBaseClientDLL *ClientSDK;
IClientEntityList *EntityListSDK;
CPrediction *PredictionSDK;
CGameMovement *GameMovementSDK;
IVEngineClient *EngineSDK; 
CInput *InputSDK;
ICvar *CvarSDK;
IVModelInfoClient *ModelInfoSDK;
IEngineTrace *EngineTraceSDK;
IPhysicsSurfaceProps *PhysicsSurfacePropsSDK;
vgui::IPanel *PanelSDK;
vgui::ISurface *SurfaceSDK;
IVRenderView *RenderViewSDK;
IMaterialSystem *MaterialSystemSDK;
IVModelRender *ModelRenderSDK;
IGameEventManager2 *GameEventManagerSDK;
IVEfx *EffectsSDK;
IVDebugOverlay *DebugOverlay;